### PR TITLE
Using dockerhub instead of gcr

### PR DESCRIPTION
**Pull request by DanielePalaia**
Some scripts review/refactoring for the pipeline migration

To integrate this one toghether with: https://github.com/rabbitmq/cluster-operator/pull/1569 and https://github.com/rabbitmq/messaging-topology-operator/pull/767

because they are using it.

### CODE REVIEW

**Comment by Zerpet** [comment]
Shouldn't we use https://quay.io/ for OLM related work?

OLM is a RedHat/Openshift thing, and quay.io is RedHat's registry

**Review by Zerpet — COMMENTED** [review]
If possible, I would prefer to use [YTT](https://carvel.dev/ytt/) over `sed`. YTT is specialised to manipulate YAML, and `sed` doesn't have the same flags in MacOS and in Linux.

It think we should also use quay.io for OLM related work, given the quay.io is part of the RedHat/Openshift ecosystem.

**Comment by DanielePalaia** [comment]
@Zerpet yeah I think is better to use https://quay.io/. I notice we are using it for the cluster operator too. I try to use that one.

**Comment by DanielePalaia** [comment]
I also modified the sed with ytt! I will merge this PR for further tests!

**Pull request merged**
